### ISSUE TITLE
Determine the initial parameters

### ISSUE THREAD

**Issue by milad-ahmadi** [drNoob13/fisheyeStitcher#1]
How to set the X Y grids for the custom image?
Mask "mask_1920x1920_fovd_187.jpg" What does it do???

**Comment by drNoob13** [comment]
The X, Y grids were generated by a rigid moving least square algorithm we implemented for the C200 camera. You can try to resize your custom image to the C200 frame size (3840x1920) and see if it is acceptable. Otherwise, you may need to run your MLS on your custom images.

The mask "mask_1920x1920_fovd_187.jpg" was a very naive way to speed up the process. The mask is used for blendng. In hindsight, it is better to use binary map for the mask since jpeg compresses the pixels.

**Comment by milad-ahmadi** [comment]
Thank you for response.
I do not understand how you produce the rigid deformation file (*.yml file)?
Do you use the App or code for this?
![rightimg_crop](https://user-images.githubusercontent.com/45760486/51085038-fb237580-1748-11e9-9c1f-95dc9c3a04c3.jpg)

**Comment by drNoob13** [comment]
No, we wrote our code. It was our implementation of the [rigid moving least square deformation](http://faculty.cs.tamu.edu/schaefer/research/mls.pdf).

**Comment by drNoob13** [comment]
#3

**Comment by DuanHuiyu** [comment]
> The X, Y grids were generated by a rigid moving least square algorithm we implemented for the C200 camera. You can try to resize your custom image to the C200 frame size (3840x1920) and see if it is acceptable. Otherwise, you may need to run your MLS on your custom images.
> 
> The mask "mask_1920x1920_fovd_187.jpg" was a very naive way to speed up the process. The mask is used for blendng. In hindsight, it is better to use binary map for the mask since jpeg compresses the pixels.

Thus, I have one another question. How could I produce the mask "mask_1920x1920_fovd_187.jpg"?
We want to apply your code on other fisheye images with higher resolution. But the code reported errors.
Therefore, we want to know the method to produce the files in "utils" folder.

**Comment by drNoob13** [comment]
@DuanHuiyu : 

I have updated the code to have the binary mask and blend post automatically generated instead of using the pre-computed ones. Please pull the latest code.

Also have a look at the repo's [wiki](https://github.com/drNoob13/fisheyeStitcher/wiki).

**Comment by drNoob13** [comment]
#3 
#5

**Comment by DuanHuiyu** [comment]
Thanks for your update. However, also something wrong when running the code.
1. In line 753 of fisheyeStitcher.cpp, "mls_map_x" and "mls_map_y" are from "./utils/grid_xd_yd_3840x1920.yml.gz". I think it depends on the resolution, is it? Thus how it produced?
2. In line 607 and line 611 of fisheyeStitcher.cpp, "Worg" and "sideW" also fixed, how should I change them?
Moreover, I want to use your code with another fisheye camera whose FOV is 200, is it feasible?
By the way, we will cite your paper in our research.
Thanks for your kindness help.

**Comment by drNoob13** [comment]
Since there are many people asking for the MLS grid, I have added a [wiki section](https://github.com/drNoob13/fisheyeStitcher/wiki/How-to-create-the-MLS-%5BX,Y%5D-grids) with some matlab scripts to address this request.

> In line 607 and line 611 of fisheyeStitcher.cpp, "Worg" and "sideW" also fixed, how should I change them?

Worg is the image width of a single fisheye image in the dual-fisheye image. For example, the output of Samsung Gear360 is 3840x1920 --> Worg = 1920.

> Moreover, I want to use your code with another fisheye camera whose FOV is 200, is it feasible?

I think it is possible to try with larger FOV. But there are some hard-coded parameters in the current code. Please try to revise them to your purpose.
